/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Votes,
  IERC20VotesInterface,
} from "../../../contracts/PrivacyVotingDAOv2.sol/IERC20Votes";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getVotes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC20Votes__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20VotesInterface {
    return new Interface(_abi) as IERC20VotesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC20Votes {
    return new Contract(address, _abi, runner) as unknown as IERC20Votes;
  }
}
