/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Votes__factory } from "./IERC20Votes__factory";
export { PrivacyVotingDAOv2__factory } from "./PrivacyVotingDAOv2__factory";
