/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockGovTokenSol from "./MockGOVToken.sol";
export type { mockGovTokenSol };
import type * as privacyVotingDaoSol from "./PrivacyVotingDAO.sol";
export type { privacyVotingDaoSol };
import type * as privacyVotingDaOv2Sol from "./PrivacyVotingDAOv2.sol";
export type { privacyVotingDaOv2Sol };
import type * as verifierGroth16Sol from "./Verifier_Groth16.sol";
export type { verifierGroth16Sol };
export type { MockVerifier } from "./MockVerifier";
export type { SemaphoreVerifier } from "./SemaphoreVerifier";
