/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Votes } from "./IERC20Votes";
export type { PrivacyVotingDAOv2 } from "./PrivacyVotingDAOv2";
